In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
a = np.array([1,2,3,4,5])
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [6]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
np.array([i*2 for i in range(5)])

array([0, 2, 4, 6, 8])