In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array(range(1,6))
c = np.arange(1,6)

print(a)
print(b)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [2]:
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int32')

In [4]:
a = np.array([1,0,1,0],dtype=bool)
a

array([ True, False,  True, False])

In [5]:
a.astype("i1")

array([1, 0, 1, 0], dtype=int8)

In [6]:
d = [0.333,0.4444,0.55555]
d

[0.333, 0.4444, 0.55555]

In [7]:
np.round(d,2)

array([0.33, 0.44, 0.56])

In [8]:
e = np.array([[3,4,5,6,7,8],[4,5,6,7,8,9]])
e

array([[3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [9]:
e.shape

(2, 6)

In [10]:
e.reshape(3,4)

array([[3, 4, 5, 6],
       [7, 8, 4, 5],
       [6, 7, 8, 9]])

In [11]:
e.shape

(2, 6)

In [12]:
f = e.reshape(3,4)

In [13]:
f.shape

(3, 4)

In [14]:
f

array([[3, 4, 5, 6],
       [7, 8, 4, 5],
       [6, 7, 8, 9]])

In [15]:
f.reshape(1,12)

array([[3, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 9]])

In [16]:
f.flatten()

array([3, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 9])

In [17]:
e

array([[3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [18]:
e+1

array([[ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

In [19]:
e*3

array([[ 9, 12, 15, 18, 21, 24],
       [12, 15, 18, 21, 24, 27]])

In [20]:
g = np.array([[21,22,23,24,25,26],[27,28,29,30,31,32]])

In [21]:
e+g

array([[24, 26, 28, 30, 32, 34],
       [31, 33, 35, 37, 39, 41]])

In [22]:
e*g

array([[ 63,  88, 115, 144, 175, 208],
       [108, 140, 174, 210, 248, 288]])