In [1]:
import numpy as np

a = np.array([[3,4,5,6,7,8],[4,5,6,7,8,9]])
c = np.array([1,2,3,4,5,6])
f = np.array([[1],[2]])

print(a-c)
print(a*c)

[[2 2 2 2 2 2]
 [3 3 3 3 3 3]]
[[ 3  8 15 24 35 48]
 [ 4 10 18 28 40 54]]


In [2]:
np.hstack((a,f))

array([[3, 4, 5, 6, 7, 8, 1],
       [4, 5, 6, 7, 8, 9, 2]])

In [3]:
np.vstack((a,c))

array([[3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6]])

In [4]:
d = np.array([[1],[2]])

print(a+d)
print(a*d)

[[ 4  5  6  7  8  9]
 [ 6  7  8  9 10 11]]
[[ 3  4  5  6  7  8]
 [ 8 10 12 14 16 18]]


In [5]:
t = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17]])

t.transpose()

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [6]:
t.swapaxes(1,0)

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [7]:
t.T

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [8]:
t[1]

array([ 6,  7,  8,  9, 10, 11])

In [9]:
t[:2]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
t[:,2]

array([ 2,  8, 14])

In [11]:
t[:,2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15]])

In [12]:
t[:,2:4]=0
t

array([[ 0,  1,  0,  0,  4,  5],
       [ 6,  7,  0,  0, 10, 11],
       [12, 13,  0,  0, 16, 17]])

In [13]:
import numpy as np
h = np.arange(24).reshape((4,6))
h < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [14]:
h[h<10]=0
h

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
import numpy as np
h = np.arange(24).reshape((4,6))
h

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
np.where(h<10,0,10)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [17]:
import numpy as np
h = np.arange(24).reshape((4,6))
h.clip(8,9)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [18]:
g = np.arange(12,24).reshape(3,4)
g

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
g[[1,2],:] = g[[2,1],:]
g

array([[12, 13, 14, 15],
       [20, 21, 22, 23],
       [16, 17, 18, 19]])

In [20]:
g[:,[0,2]] = g[:,[2,0]]
g

array([[14, 13, 12, 15],
       [22, 21, 20, 23],
       [18, 17, 16, 19]])